// <auto-generated />
using System;
using MicroservicioAsignacionCalendario.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroservicioAsignacionCalendario.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109163006_initMicroAsign")]
    partial class initMicroAsign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaFin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() + INTERVAL '2 weeks'");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlanEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionActual")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervaloDiasDescanso")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlumnoPlan", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EjercicioRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionRealizada")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreEjercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PesoObjetivo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RepeticionesObjetivo")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSesionRealizada");

                    b.ToTable("EjercicioRegistro", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EventoCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAlumnoPlan")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEntrenador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventoCalendario", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.RecordPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreEjercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecordPersonal", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaRealizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdPlanAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdPlanAlumno");

                    b.ToTable("SesionRealizada", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EjercicioRegistro", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", "SesionRealizada")
                        .WithMany("EjerciciosRegistrados")
                        .HasForeignKey("IdSesionRealizada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SesionRealizada");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", "AlumnoPlan")
                        .WithMany("SesionesRealizadas")
                        .HasForeignKey("IdPlanAlumno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlumnoPlan");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", b =>
                {
                    b.Navigation("SesionesRealizadas");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.Navigation("EjerciciosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
