// <auto-generated />
using System;
using MicroservicioAsignacionCalendario.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroservicioAsignacionCalendario.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionPlan")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlanEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionARealizar")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervaloDiasDescanso")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlumnoPlan", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EjercicioRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DescansoObjetivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEjercicioSesion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionRealizada")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("NombreEjercicio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreGrupoMuscular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreMusculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrdenEjercicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PesoObjetivo")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RepeticionesObjetivo")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("int");

                    b.Property<string>("UrlDemoEjercicio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSesionRealizada");

                    b.ToTable("EjercicioRegistro", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EventoCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAlumnoPlan")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumnoPlan");

                    b.ToTable("EventoCalendario", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.RecordPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calculo1RM")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAlumnoPlan")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEjercicioSesion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionRealizada")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreEjercicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreGrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PesoMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumnoPlan");

                    b.HasIndex("IdSesionRealizada");

                    b.HasIndex("IdAlumno", "IdEjercicio")
                        .IsUnique();

                    b.ToTable("RecordPersonal", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AlturaEnCmAlumno")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAlumnoPlan")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreSesion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrdenSesion")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoCorporalAlumno")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumnoPlan");

                    b.ToTable("SesionRealizada", (string)null);
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EjercicioRegistro", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", "SesionRealizada")
                        .WithMany("EjerciciosRegistrados")
                        .HasForeignKey("IdSesionRealizada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionRealizada");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.EventoCalendario", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", "AlumnoPlan")
                        .WithMany("EventosCalendarios")
                        .HasForeignKey("IdAlumnoPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlumnoPlan");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.RecordPersonal", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", "AlumnoPlan")
                        .WithMany("RecordsPersonales")
                        .HasForeignKey("IdAlumnoPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", "SesionRealizada")
                        .WithMany()
                        .HasForeignKey("IdSesionRealizada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlumnoPlan");

                    b.Navigation("SesionRealizada");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.HasOne("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", "AlumnoPlan")
                        .WithMany("SesionesRealizadas")
                        .HasForeignKey("IdAlumnoPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlumnoPlan");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.AlumnoPlan", b =>
                {
                    b.Navigation("EventosCalendarios");

                    b.Navigation("RecordsPersonales");

                    b.Navigation("SesionesRealizadas");
                });

            modelBuilder.Entity("MicroservicioAsignacionCalendario.Domain.Entities.SesionRealizada", b =>
                {
                    b.Navigation("EjerciciosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
